#!/bin/bash

cd $(dirname $0)/..

function die() {
  echo "$1"
  exit 1
}

which sm2 &>/dev/null || die "Can't find Service Manager"

sm2 --start ITSA_SOFTWARE_CHOICES_ALL "$@"

sleep 5
sm2 --stop INCOME_TAX_SOFTWARE_CHOICES_FRONTEND
sleep 5
sbt "run 9591 -Dapplication.router=testOnlyDoNotUseInAppConf.Routes"
